### PR TITLE
fix: unify the logged output of the task result

### LINKED ISSUE #179: TaskLog expects a string to be set as an output, but Events::trigger() returns bool
I have written the events with schedule to run every hour But it throw error
```
TypeError: Cannot assign true to property CodeIgniter\Tasks\TaskLog::$output of type ?string
```

```php
    public static function sent_unqueue_mail()
    {
        $repo     = new SQLEmail_listRepository();
        $data     = $repo->getUnQueueJobs();
        $totalJob = 0;
        if (is_array($data) && count($data)) {
            $eLib = new \Mail\Libraries\Email();
            foreach ($data as $k => $v) {
                try {
                    $eLib->send($v);
                    $totalJob++;
                } catch (\Exception $e) {
                    log_message('error', "Failed to send email for job $k: " . $e->getMessage());
                }
            }
        }
        log_message('info', "Sent Unqueue Completed $totalJob");
        return ["Sent Unqueue Completed"];
    }
```

I assigned events
```php
Events::on('sent_unqueue_mail', '\Mail\Events\EventsMail::sent_unqueue_mail');
```

please help me to resolve this issues

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes a bug where the task result cannot always be logged properly.

Fixes #179

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: src/TaskLog.php [hunk 1]
```diff
@@ -68,4 +70,24 @@ public function __get(string $key)
...
     }
+
+    /**
+     * Unify output to string.
+     *
+     * @param array|bool|int|string|null $value
+     *
+     * @return string|null
+     */
+    protected function setOutput($value)
```
Comment (paulbalandan) [inline src/TaskLog.php]: This can use native return and set to private.
```suggestion
    private function setOutput($value): ?string
```

File: src/TaskLog.php [hunk 2]
```diff
@@ -68,4 +70,24 @@ public function __get(string $key)
             return $this->{$key};
         }
     }
+
+    /**
+     * Unify output to string.
+     *
+     * @param array|bool|int|string|null $value
```
Comment (paulbalandan) [inline src/TaskLog.php]: Can you specify what the array accepts?

**Comment by michalsn** [comment]
Fixed. Not sure why rector is always failing at first and I have to run it again.

Maybe we should add these lines to the file in this repo: https://github.com/codeigniter4/.github/blob/main/.github/workflows/rector.yml#L22-L27

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
It seems it already uses the concurrency thing as it inherits from the `.github` repo. But I'm not sure why it's taking so long to start.

**Comment by michalsn** [comment]
Thank you!

I had to manually restart the rector and now it went in no time 🤷‍♂️
